### ISSUE TITLE
这个底部是杂回事？

### ISSUE THREAD

**Issue by mtgq** [ITmonkey-cn/shopro-uniapp#10]
![image](https://user-images.githubusercontent.com/29910922/131827999-e6742988-654d-441b-a625-aacc575cc2e5.png)
我把代码拉下来，运行后这个页面出现异常

**Comment by ITmonkey-cn** [comment]
哪个版本，具体复现流程，没有复现这个问题

**Comment by mtgq** [comment]
> 哪个版本，具体复现流程，没有复现这个问题

就 git 下载的最新版本，在我本地运行的

**Comment by mtgq** [comment]
> 哪个版本，具体复现流程，没有复现这个问题

找到问题了，我本地是 "uview-ui": "^1.8.4", 这个版本，项目中的版本比较低
