### ISSUE TITLE
还在更新吗？我看好久都没更新了

### ISSUE THREAD

**Issue by mtgq** [ITmonkey-cn/shopro-uniapp#17]

**Comment by lixiaofa** [comment]
你也在dom , 这个小程序吗 ， 你的小程序能登录吗 ， 我这边为什么登录不了， 微信登录 ， 望指点一下， 谢谢

**Comment by selson** [comment]
人气做起来，搞成收费的了。

**Comment by yjt1216** [comment]
> 人气做起来，搞成收费的了。

你可以用vue3  可以登录
毕竟服务器 需要维护

**Comment by qurge** [comment]
> > 人气做起来，搞成收费的了。
> 
> 你可以用vue3 可以登录 毕竟服务器 需要维护

v3在哪？收费吗？

**Comment by yjt1216** [comment]
> 

gite中直接搜shopro-uniapp

**Comment by qurge** [comment]
> > 
> 
> gite中直接搜shopro-uniapp

好的，感谢大佬
