### ISSUE TITLE
代码下载下来后怎么在HbuilderX运行呢

### ISSUE THREAD

**Issue by AvadaKedavra000** [ITmonkey-cn/shopro-uniapp#7]
新手，如题。npm相关的依赖都已经安装，但是打开浏览器是空白的，微信开发者工具也无法打开，求教

**Comment by ITmonkey-cn** [comment]
1. 先配置HbuilderX,运行配置里面，有浏览器运行配置，小程序运行配置
![image](https://user-images.githubusercontent.com/44823771/122851326-55c15280-d341-11eb-8114-40e518a3c484.png)
2. 然后在编辑器中运行。
![image](https://user-images.githubusercontent.com/44823771/122851220-2f031c00-d341-11eb-9f69-a6ba76809c5d.png)
